[package]
name = "noise"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.41"
ed25519-dalek = "1.0.1"
snow = "0.8.0"
thiserror = "1.0.25"
x25519-dalek = "1.1.1"
rand = "0.7.0"
